### ISSUE TITLE
Error installing plugin...

### ISSUE THREAD

**Issue by marcobra** [geometalab/HTML-Image-Map-Creator-QGIS-Plugin#22]
Win7, 64BIT installing plugin qgis 2.18.x

```
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 308, in loadPlugin
    __import__(packageName)
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "[cut]/.qgis2/python/plugins\HTML-Image-Map-Creator\__init__.py", line 1, in 
    from html_image_map_creator_plugin import HTMLImageMapCreatorPlugin
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "[cut]/.qgis2/python/plugins\HTML-Image-Map-Creator\html_image_map_creator_plugin.py", line 9, in 
    from html_image_map_creator_gui import HTMLImageMapCreatorGUI
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "[cut]/.qgis2/python/plugins\HTML-Image-Map-Creator\html_image_map_creator_gui.py", line 12, in 
    import html_image_map_creator_rc
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named html_image_map_creator_rc
```

**Comment by sfkeller** [comment]
See #21
